GET http://localhost:8080/data
content-type: application/json

{
  "email": "akulasaht@gmail.com",
  "current_dateTime": "2025-01-20T09:57:00.000Z",
  "git_hub": "https://github.com/AkulasahTonye/API_Testing"
}